server:
  port: ${PORT:8761}
 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://localhost:${PORT:8761}}/eureka/

info:
  service:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'