server:
  port: ${PORT:8761}
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

info:
  service:
    name: service-registry
    description: Spring Microservices Service Registry
    version: 1.0.0-SNAPSHOT